#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using DataKeeper.GameTagSystem;
using UnityEditor;
using UnityEngine;

namespace DataKeeper.Editor.GameTagSystem
{
    /// <summary>
    /// Generates a typed <c>GameTags</c> tree from the registry so code can reference tags with
    /// compile-time safety, IntelliSense and find-usages:
    ///   leaf   ->  GameTags.Enemy.Boss.Elite      (a GameTag field)
    ///   branch ->  GameTags.Enemy.Boss.Self       (the branch's own tag; children nest under it)
    /// A branch is a class (so children can nest), so its own tag lives on the reserved <c>Self</c>.
    /// References are by stable id, so renaming a node only changes the generated identifier — every
    /// affected code site is flagged by the compiler, while data references keep working untouched.
    /// </summary>
    public static class GameTagsCodeGen
    {
        private const string OutputFileName = "GameTags.g.cs";
        private const string SelfMember = "Self";

        private static readonly HashSet<string> Keywords = new()
        {
            "abstract","as","base","bool","break","byte","case","catch","char","checked","class","const",
            "continue","decimal","default","delegate","do","double","else","enum","event","explicit","extern",
            "false","finally","fixed","float","for","foreach","goto","if","implicit","in","int","interface",
            "internal","is","lock","long","namespace","new","null","object","operator","out","override","params",
            "private","protected","public","readonly","ref","return","sbyte","sealed","short","sizeof","stackalloc",
            "static","string","struct","switch","this","throw","true","try","typeof","uint","ulong","unchecked",
            "unsafe","ushort","using","virtual","void","volatile","while"
        };

        [InitializeOnLoadMethod]
        private static void Register() => GameTagRegistry.RegenerateCodeHook = Regenerate;

        public static void Regenerate(GameTagRegistry registry)
        {
            if (registry == null)
            {
                Debug.LogWarning("[GameTagsCodeGen] No GameTagRegistry — nothing to generate.");
                return;
            }
            registry.Bake();

            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated by DataKeeper GameTagsCodeGen — do not edit by hand.");
            sb.AppendLine("//     Regenerate via the \"Regenerate GameTags Class\" button on the GameTagRegistry asset.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using DataKeeper.GameTagSystem;");
            sb.AppendLine();
            sb.AppendLine("public static partial class GameTags");
            sb.AppendLine("{");

            var roots = new List<int>(registry.RootIds);
            roots.Sort((a, b) => string.CompareOrdinal(registry.GetName(a), registry.GetName(b)));

            var rootScope = new HashSet<string>();
            foreach (var id in roots)
                EmitNode(registry, id, 1, rootScope, sb);

            sb.AppendLine("}");

            WriteIfChanged(ResolveOutputPath(registry), sb.ToString());
        }

        // Writes the generated class next to the registry asset, wherever that lives.
        private static string ResolveOutputPath(GameTagRegistry registry)
        {
            string assetPath = AssetDatabase.GetAssetPath(registry);
            string dir = string.IsNullOrEmpty(assetPath) ? "Assets" : Path.GetDirectoryName(assetPath);
            return $"{dir}/{OutputFileName}".Replace('\\', '/');
        }

        private static void EmitNode(GameTagRegistry registry, int id, int indent, HashSet<string> scope, StringBuilder sb)
        {
            var node = registry.GetNode(id);
            if (node == null) return;

            string pad = new string(' ', indent * 4);
            string ident = UniqueIdentifier(node.Name, scope);

            if (node.Children.Count == 0)
            {
                sb.AppendLine($"{pad}public static readonly GameTag {ident} = GameTag.FromId({id}); // {node.Path}");
                return;
            }

            sb.AppendLine($"{pad}public static class {ident}");
            sb.AppendLine($"{pad}{{");
            sb.AppendLine($"{pad}    public static readonly GameTag {SelfMember} = GameTag.FromId({id}); // {node.Path}");

            var childScope = new HashSet<string> { SelfMember }; // reserve so a child named "Self" is renamed
            var children = new List<int>(node.Children);
            children.Sort((a, b) => string.CompareOrdinal(registry.GetName(a), registry.GetName(b)));
            foreach (var childId in children)
                EmitNode(registry, childId, indent + 1, childScope, sb);

            sb.AppendLine($"{pad}}}");
        }

        // Sanitize a tag segment into a unique, valid C# identifier within its scope.
        private static string UniqueIdentifier(string raw, HashSet<string> scope)
        {
            var sb = new StringBuilder(raw.Length + 1);
            foreach (var ch in raw)
                sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');

            string name = sb.ToString();
            if (string.IsNullOrEmpty(name)) name = "_";
            if (char.IsDigit(name[0])) name = "_" + name;
            if (Keywords.Contains(name)) name = "@" + name;

            string baseName = name;
            int i = 2;
            while (!scope.Add(name))
                name = baseName + "_" + i++;
            return name;
        }

        private static void WriteIfChanged(string path, string content)
        {
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            if (File.Exists(path) && File.ReadAllText(path) == content)
                return; // no change — avoid a needless recompile

            File.WriteAllText(path, content);
            AssetDatabase.ImportAsset(path);
            Debug.Log($"[GameTagsCodeGen] Wrote {path}");
        }
    }
}
#endif
